# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: Project File is never complete
description: You might as well click around, since you found this stuff
baseurl: "https://mwmxyz.github.io/no_this_is_wrong/"
url: https://mwmxyz.github.io/academic/

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: Michael W. Merriam
  description:
    - I'm sorry about the mess...
    - Wait, why am I apologizing to you? You're in someone else's... green place!
    - I'm sorry I snapped at you. Make yourself at home. Did you enjoy the nice, well-manicured CV?
  cv: https://mwmxyz.github.io/academic/
  address:
    - University of Jekyll
    - Department of Themes
    - 123 Main St, Anytown, USA
  contact:
    office: Foobar Hall 1.23
    phone: +1 234 567 890
    email: username@domain.com
  demo: https://hacked-jekyll.netlify.app
  source: https://github.com/piazzai/hacked-jekyll
  profiles:
    facebook: https://www.facebook.com
    twitter: https://twitter.com
    instagram: https://www.instagram.com
    linkedin: https://www.linkedin.com
    stackoverflow: https://stackoverflow.com
    github: https://github.com

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
